MODELS:
  OPENAI:
    API_KEY: gAAAAABqWkEbm_n6jiDbQ9NMfGY3-cy1wZIWJQeA6ce7jY-Li_axAdTRsN6mePoLs3GmhbiEn37BjhDGYhkuRnw-QI_ENXHr1Q==
  ANTHROPIC:
    API_KEY: gAAAAABqWkEg7Fg16TVzzxmKO2l9LObVlafgiQ0NG3CaAxOQ5MNFx-Ls02IHANxMrJZ_rKvz-wHMWPO-VMAv0lknDV6S5iGyWQ==
  GEMINI:
    API_KEY: NOT_CONFIGURED
EMBEDDING:
  MODEL_NAME: minishlab/potion-base-8M
RATE_LIMITER:
  MAX_TOKENS: '500'
  REFILL_RATE: '100'
  TIME_INTERVAL: '1.0'
GATEWAY:
  DEFAULT_MODEL: claude-opus-4-6
  DEFAULT_TEMPERATURE: '0.7'
ADMIN:
  USERNAME: gAAAAABqWkEN_NB_-YGGxxZEdIkuNrtK862R6F0QGbmuFM8LFyA9s8_uS0_lOBdBvHZRvNZyiBPnyfigpXCKIN05C-GMZPm4tA==
  PASSWORD_HASH: oZBHOvsL+3ts2MZNUntuc9rMaunDONZ+3Di2c4xBcwPz1RQJ9bJ4z9z8CopXUSBw
