models:
  openai:
    api_key: NOT_CONFIGURED
  anthropic:
    api_key: gAAAAABqWzq6Ch4Eps4FwY4jisCNW1cGAvvvmxANaUKQ-b53GvVu3-kVpye0MMmnikPeCtMHktkkboy6lAhW8jZzjgPGitP75-XKTQFholjPYoqz2zGzjlfu_DF_gz8LQcrA5sGX_3cGj30HHrCpqwjexdi3gpEhFdgn5I05Fd87If-8f-4R1V_Xa5GVvSdka4IfrDsykaErsfoZiV7HRyl-hAG019GmfA==
  gemini:
    api_key: NOT_CONFIGURED
embedding:
  model_name: minishlab/potion-base-8M
rate_limiter:
  max_tokens: '500'
  refill_rate: '100'
  time_interval: '1.0'
gateway:
  default_model: claude-sonnet-4-6
  default_temperature: '0.7'
admin:
  username: gAAAAABqWzq0ZuolfIXp3sv5EVKviJouF_ZUfgRlNoSwjYoTr2mwIi-cdpTGwHqnMkz2wMLktIfF4PANnIw7rkQUy3yw0eAj2A==
  password_hash: s/TD1HuGAbptmjmfB8HsUrxisO6JMz/HWwu892qpLonaoocmJs3HAL4wra2UEhp8
