from typing import Literal, TypedDict

REDIS_STREAM_NAMES = Literal["RESPONSE_CACHE"]
REPOSITORY_TYPE = Literal["EMBEDDING", "DATABASE", "VECTOR_DB", "CACHE", "ROUTER"]
ADAPTER_TYPE = Literal["CHAT"]
CONFIGURATION_SECTIONS = Literal["OPENAI", "ANTHROPIC", "LLAMA"]
CONFIGURATION_OPTIONS = Literal["ENDPOINT", "API_KEY"]

CACHE_TYPE = Literal["EXACT", "SEMANTIC"]


