from typing import Literal

REDIS_STREAM_NAMES = Literal["RESPONSE_CACHE", "ANALYTICS"]
REPOSITORY_TYPE = Literal["EMBEDDING", "DATABASE", "VECTOR_DB", "CACHE", "ROUTER", "RANKING"]
ADAPTER_TYPE = Literal["CHAT"]
CONFIGURATION_SECTIONS = Literal["MODELS", "EMBEDDING", "RATE_LIMITER", "GATEWAY"]
CONFIGURATION_OPTIONS = Literal["ENDPOINT", "API_KEY", "MODEL_NAME", "MAX_TOKENS", "REFILL_RATE", "TIME_INTERVAL", "DEFAULT_MODEL"]
CONFIGURATION_SUB_SECTIONS = Literal["OPENAI", "ANTHROPIC", "GEMINI", None]
LLM_PROVIDER = Literal["OPENAI", "ANTHROPIC", "GEMINI", "EMBEDDING"]
QUEUE_TYPE = Literal["REDIS_STREAM"]

CACHE_TYPE = Literal["EXACT", "SEMANTIC"]

VECTOR_REPOSITORY_COLLECTIONS = Literal["semantic_cache", "intelligence_classifier_cache"]

