from typing import Literal, TypedDict

REDIS_STREAM_NAMES = Literal["RESPONSE_CACHE"]
REPOSITORY_TYPE = Literal["EMBEDDING", "DATABASE", "VECTOR_DB", "CACHE", "ROUTER"]
ADAPTER_TYPE = Literal["CHAT"]
CONFIGURATION_SECTIONS = Literal["OPENAI", "ANTHROPIC", "GEMINI", "EMBEDDING", "RATE_LIMITER", "GATEWAY"]
CONFIGURATION_OPTIONS = Literal["ENDPOINT", "API_KEY", "MODEL_NAME", "MAX_TOKENS", "REFILL_RATE", "TIME_INTERVAL"]
LLM_PROVIDER = Literal["OPENAI", "ANTHROPIC", "GEMINI", "EMBEDDING"]
QUEUE_TYPE = Literal["REDIS_STREAM"]

CACHE_TYPE = Literal["EXACT", "SEMANTIC"]


